library(foreign)
library(lubridate)
#library(latticeExtra)
####### Figure 1 #######
Year<-c(rep(2003,12),rep(2004,12),rep(2005,12),rep(2006,12),rep(2007,12),rep(2008,12),
        rep(2009,12),rep(2010,12),rep(2011,12),rep(2012,12),rep(2013,12),rep(2014,12),
        rep(2015,12),rep(2016,12),rep(2017,12),rep(2018,12))
# Amazonas
setwd("C:/Users/Mario Cañon/ownCloud/malaria/Analises Mario/Dados/Artigo malaria Journal/Bayesian models and incidence prediction/AM")
load(file="AM_pre_viv.rdata")
AM_viv<-data.frame(t=Inci$i,Estado=rep(13,192),Inci_viv=Inci$Y,Pre_viv=Inci$Pre)
load(file="AM_pre_fal.rdata")
AM<-data.frame(AM_viv,Inci_fal=Inci$Y,Pre_fal=Inci$Pre,Year)
# Acre
setwd("C:/Users/Mario Cañon/ownCloud/malaria/Analises Mario/Dados/Artigo malaria Journal/Bayesian models and incidence prediction/AC")
load(file="AC_pre_viv.rdata")
AC_viv<-data.frame(t=Inci$i,Estado=rep(12,192),Inci_viv=Inci$Y,Pre_viv=Inci$Pre)
load(file="AC_pre_fal.rdata")
AC<-data.frame(AC_viv,Inci_fal=Inci$Y,Pre_fal=Inci$Pre,Year)
# Rondonia
setwd("C:/Users/Mario Cañon/ownCloud/malaria/Analises Mario/Dados/Artigo malaria Journal/Bayesian models and incidence prediction/RO")
load(file="RO_pre_viv.rdata")
RO_viv<-data.frame(t=Inci$i,Estado=rep(11,192),Inci_viv=Inci$Y,Pre_viv=Inci$Pre)
load(file="RO_pre_fal.rdata")
RO<-data.frame(RO_viv,Inci_fal=Inci$Y,Pre_fal=Inci$Pre,Year)
# Pará
setwd("C:/Users/Mario Cañon/ownCloud/malaria/Analises Mario/Dados/Artigo malaria Journal/Bayesian models and incidence prediction/PA")
load(file="PA_pre_viv.rdata")
PA_viv<-data.frame(t=Inci$i,Estado=rep(15,192),Inci_viv=Inci$Y,Pre_viv=Inci$Pre)
load(file="PA_pre_fal.rdata")
PA<-data.frame(PA_viv,Inci_fal=Inci$Y,Pre_fal=Inci$Pre,Year)
# Amapá
setwd("C:/Users/Mario Cañon/ownCloud/malaria/Analises Mario/Dados/Artigo malaria Journal/Bayesian models and incidence prediction/AP")
load(file="AP_pre_viv.rdata")
AP_viv<-data.frame(t=Inci$i,Estado=rep(16,192),Inci_viv=Inci$Y,Pre_viv=Inci$Pre)
load(file="AP_pre_fal.rdata")
AP<-data.frame(AP_viv,Inci_fal=Inci$Y,Pre_fal=Inci$Pre,Year)
# Roraima
setwd("C:/Users/Mario Cañon/ownCloud/malaria/Analises Mario/Dados/Artigo malaria Journal/Bayesian models and incidence prediction/RR")
load(file="RR_pre_viv.rdata")
RR_viv<-data.frame(t=Inci$i,Estado=rep(14,192),Inci_viv=Inci$Y,Pre_viv=Inci$Pre)
load(file="RR_pre_fal.rdata")
RR<-data.frame(RR_viv,Inci_fal=Inci$Y,Pre_fal=Inci$Pre,Year)
# Mato Grosso
setwd("C:/Users/Mario Cañon/ownCloud/malaria/Analises Mario/Dados/Artigo malaria Journal/Bayesian models and incidence prediction/MT")
load(file="MT_pre_viv.rdata")
MT_viv<-data.frame(t=Inci$i,Estado=rep(51,192),Inci_viv=Inci$Y,Pre_viv=Inci$Pre)
load(file="MT_pre_fal.rdata")
MT<-data.frame(MT_viv,Inci_fal=Inci$Y,Pre_fal=Inci$Pre,Year)
# Maranhao
setwd("C:/Users/Mario Cañon/ownCloud/malaria/Analises Mario/Dados/Artigo malaria Journal/Bayesian models and incidence prediction/MA")
load(file="MA_pre_viv.rdata")
MA_viv<-data.frame(t=Inci$i,Estado=rep(21,192),Inci_viv=Inci$Y,Pre_viv=Inci$Pre)
load(file="MA_pre_fal.rdata")
MA<-data.frame(MA_viv,Inci_fal=Inci$Y,Pre_fal=Inci$Pre,Year)
# Tocantins
setwd("C:/Users/Mario Cañon/ownCloud/malaria/Analises Mario/Dados/Artigo malaria Journal/Bayesian models and incidence prediction/TO")
load(file="TO_pre_viv.rdata")
TO_viv<-data.frame(t=Inci$i,Estado=rep(17,192),Inci_viv=Inci$Y,Pre_viv=Inci$Pre)
load(file="TO_pre_fal.rdata")
TO<-data.frame(TO_viv,Inci_fal=Inci$Y,Pre_fal=Inci$Pre,Year)
##### BASE TOTAL #####
BASE_PRE<-rbind(AM,AC,RO,PA,RR,AP,MT,MA,TO)
#### 
setwd("C:/Users/Mario Cañon/ownCloud/malaria/Analises Mario/Dados/Artigo malaria Journal/Bayesian models and incidence prediction")
pdf(paste("Figure_1.pdf"),width=8.5,height=6.5,paper='special')
par(mfrow=c(3,3),mar=c(2,4,1.8,1)) #mar=c(1.5,2.5,1.5,0.5)
dates <- seq(as.Date("01/01/2003", format = "%d/%m/%Y"), by = "months", length = 192)
plot(dates,AM$Inci_viv,type="l",col="blue",ylim=c(0,max(AM$Inci_viv)),ylab="incidence",xlab="",lwd=2,main="Amazonas")
lines(dates,AM$Pre_viv,type="l",col="darkorange1",lwd=1,lty=1)
lines(dates,AM$Inci_fal,type="l",col="darkgreen",lwd=2)
lines(dates,AM$Pre_fal,type="l",col="red",lwd=1,lty=1)
abline(v=dates[157], lty=2, lwd=1,col="black")
plot(dates,AC$Inci_viv,type="l",col="blue",ylim=c(0,max(AC$Inci_viv)),ylab="",xlab="",lwd=2,main="Acre")
lines(dates,AC$Pre_viv,type="l",col="darkorange1",lwd=1,lty=1)
lines(dates,AC$Inci_fal,type="l",col="darkgreen",lwd=2)
lines(dates,AC$Pre_fal,type="l",col="red",lwd=1,lty=1)
abline(v=dates[157], lty=2, lwd=1,col="black")
plot(dates,PA$Inci_viv,type="l",col="blue",ylim=c(0,max(PA$Inci_viv)),ylab="",xlab="",lwd=2,main="Pará")
lines(dates,PA$Pre_viv,type="l",col="darkorange1",lwd=1,lty=1)
lines(dates,PA$Inci_fal,type="l",col="darkgreen",lwd=2)
lines(dates,PA$Pre_fal,type="l",col="red",lwd=1,lty=1)
abline(v=dates[157], lty=2, lwd=1,col="black")
plot(dates,AP$Inci_viv,type="l",col="blue",ylim=c(0,max(AP$Inci_viv)),ylab="incidence",xlab="",lwd=2,main="Amapá")
lines(dates,AP$Pre_viv,type="l",col="darkorange1",lwd=1,lty=1)
lines(dates,AP$Inci_fal,type="l",col="darkgreen",lwd=2)
lines(dates,AP$Pre_fal,type="l",col="red",lwd=1,lty=1)
abline(v=dates[157], lty=2, lwd=1,col="black")
plot(dates,RR$Inci_viv,type="l",col="blue",ylim=c(0,max(RR$Inci_viv)),ylab="",xlab="",lwd=2,main="Roraima")
lines(dates,RR$Pre_viv,type="l",col="darkorange1",lwd=1,lty=1)
lines(dates,RR$Inci_fal,type="l",col="darkgreen",lwd=2)
lines(dates,RR$Pre_fal,type="l",col="red",lwd=1,lty=1)
abline(v=dates[157], lty=2, lwd=1,col="black")
plot(dates,RO$Inci_viv,type="l",col="blue",ylim=c(0,max(RO$Inci_viv)),ylab="",xlab="",lwd=2,main="Rondônia")
lines(dates,RO$Pre_viv,type="l",col="darkorange1",lwd=1,lty=1)
lines(dates,RO$Inci_fal,type="l",col="darkgreen",lwd=2)
lines(dates,RO$Pre_fal,type="l",col="red",lwd=1,lty=1)
abline(v=dates[157], lty=2, lwd=1,col="black")
legend("topright", legend=c("P. vivax data","P. vivax prediction","P. falciparum data","P. falciparum prediction"),
       col=c("blue","darkorange1","darkgreen","red"),lty=c(1,1,1,1),lwd=c(1.5,1.5,1.5,1.5), cex=0.7,bg='white')
plot(dates,MT$Inci_viv,type="l",col="blue",ylim=c(0,max(MT$Inci_viv)),ylab="incidence",xlab="year",lwd=2,main="Mato Grosso")
lines(dates,MT$Pre_viv,type="l",col="darkorange1",lwd=1,lty=1)
lines(dates,MT$Inci_fal,type="l",col="darkgreen",lwd=2)
lines(dates,MT$Pre_fal,type="l",col="red",lwd=1,lty=1)
abline(v=dates[157], lty=2, lwd=1,col="black")
plot(dates,MA$Inci_viv,type="l",col="blue",ylim=c(0,max(MA$Inci_viv)),ylab="",xlab="year",lwd=2,main="Maranhão")
lines(dates,MA$Pre_viv,type="l",col="darkorange1",lwd=1,lty=1)
lines(dates,MA$Inci_fal,type="l",col="darkgreen",lwd=2)
lines(dates,MA$Pre_fal,type="l",col="red",lwd=1,lty=1)
abline(v=dates[157], lty=2, lwd=1,col="black")
plot(dates,TO$Inci_viv,type="l",col="blue",ylim=c(0,max(TO$Inci_viv)),ylab="incidence",xlab="year",lwd=2,main="Tocantins")
lines(dates,TO$Pre_viv,type="l",col="darkorange1",lwd=1,lty=1)
lines(dates,TO$Inci_fal,type="l",col="darkgreen",lwd=2)
lines(dates,TO$Pre_fal,type="l",col="red",lwd=1,lty=1)
abline(v=dates[157], lty=2, lwd=1,col="black")
dev.off()